gesture:
  click_threshold: 40.0
  scroll_threshold: 40.0
  finger_spacing_threshold: 30.0
smoothing:
  alpha: 0.3
camera:
  index: 0
  width: 1280
  height: 720
region_of_interest:
  enabled: true
  x_min: 0.203
  x_max: 1.034
  y_min: 0.126
  y_max: 1.007
